### PR TITLE
Conditional Monge drug ood experiments (mlflow and checkpointing changes)

### PR DESCRIPTION
**Pull request by DriessenA**

### CODE REVIEW

**Comment by jannisborn** [comment]
Unfortunately there are some conflicts with the base branch that have to be resolved before the PR can be reviewed

**Comment by DriessenA** [comment]
Should be good now? All checks have passed at least :)

**Comment by jannisborn** [comment]
I think we can close this PR @DriessenA right?

**Comment by DriessenA** [comment]
Yes we can close

**Pull request closed without merging**
