### PR TITLE
Updating utils from CAROT to CMonge

### PR DESCRIPTION
**Pull request by DriessenA**
Adding generic utils from CAROT to CMonge

### CODE REVIEW

**Review by jannisborn — CHANGES_REQUESTED** [review]
Why moving from `utils` to `analysis`, that's inducing an unnecessary breaking change.

If you have to move it, create a dummy import from the utils file to ensure backwards compatibility

**Comment by DriessenA** [comment]
> Why moving from `utils` to `analysis`, that's inducing an unnecessary breaking change.
> 
> If you have to move it, create a dummy import from the utils file to ensure backwards compatibility

Soo if I add the typing of ConditionDataModule and ConditionalMongeTrainer etc, there are circular imports. This only breaks a few notebooks (mostly in the CARs) which I have already changes.

**Comment by jannisborn** [comment]
Alright but type hints are not enough of a reason to induce a breaking change in a pypi package. Let's use strings instead as recommended by PEP conventions https://peps.python.org/pep-0484/#forward-references

**Comment by DriessenA** [comment]
> Alright but type hints are not enough of a reason to induce a breaking change in a pypi package. Let's use strings instead as recommended by PEP conventions https://peps.python.org/pep-0484/#forward-references

So I tried this, if I don't import the modules, I still get `<module> not defined` errors and if I do import the modules it still get's a circular import error.

**Pull request merged**
